### ISSUE TITLE
What about offline mode?

### ISSUE THREAD

**Issue by Limyx826** [marcussacana/TBF#2]
I haven't touch tales of berseria for a while but when I start it just now it pop up steam is in offline mode. 
When I remove TBF it works again. Please look into this problem. I try to check into the source code for this issue too.

By the way, I am using Visual Studio 2017 and still kind of a newbie in this.

**Comment by marcussacana** [comment]
steam offline mode error is a denuvo window
Well... the problem is your windows has  been updated and isn't working the TBF now...
try read this: https://github.com/marcussacana/TBF/issues/1
